services:

  app:
    image: message-manager-app
    container_name: message-manager-app
    restart: unless-stopped
    pull_policy: build
    build:
      context: ./MessageManager
      dockerfile: Dockerfile
    ports:
      - ${MESSAGE_MANAGER_PORT}:5212
    networks:
      - message-manager-network
    env_file:
      - path: stack.env
        required: false
      - path: .env
        required: false
    environment:
        - ConnectionStrings__MessageDb=${MESSAGE_MANAGER_MESSAGE_DB_CONNECTION_STRING}
        - ConnectionStrings__IdentityDb=${MESSAGE_MANAGER_MESSAGE_DB_CONNECTION_STRING}
    depends_on:
      - database

  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: database
    restart: unless-stopped
    networks:
      - message-manager-network
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${MESSAGE_MANAGER_DB_PASSWORD}
    env_file:
      - path: stack.env
        required: false
      - path: .env
        required: false
    ports:
      - ${MESSAGE_MANAGER_DB_PORT}:1433
    volumes:
      - sqldata:/var/opt/mssql

networks:
  message-manager-network:
    driver: bridge

volumes:
  sqldata:
