// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Editor.Migrations
{
    [DbContext(typeof(MessageContext))]
    [Migration("20190722055031_AddAudioTable")]
    partial class AddAudioTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Editor.Models.Audio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DownloadUrl")
                        .IsRequired();

                    b.Property<int>("MessageId");

                    b.Property<string>("StreamUrl")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.ToTable("Audio");
                });

            modelBuilder.Entity("Editor.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AudioId");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4095);

                    b.Property<int?>("NotesId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120);

                    b.Property<int?>("VideoId");

                    b.HasKey("Id");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("Editor.Models.Notes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("MessageId");

                    b.Property<string>("Url")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("Editor.Models.Video", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("MessageId");

                    b.Property<DateTime>("MessageStartTime");

                    b.Property<string>("YouTubePlaylistId");

                    b.Property<string>("YouTubeVideoId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.ToTable("Video");
                });

            modelBuilder.Entity("Editor.Models.Audio", b =>
                {
                    b.HasOne("Editor.Models.Message", "Message")
                        .WithOne("Audio")
                        .HasForeignKey("Editor.Models.Audio", "MessageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Editor.Models.Notes", b =>
                {
                    b.HasOne("Editor.Models.Message", "Message")
                        .WithOne("Notes")
                        .HasForeignKey("Editor.Models.Notes", "MessageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Editor.Models.Video", b =>
                {
                    b.HasOne("Editor.Models.Message", "Message")
                        .WithOne("Video")
                        .HasForeignKey("Editor.Models.Video", "MessageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
